  version: '3.8'

services:
  mysql:
    image: mysql:8-oracle
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: door_waar
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    restart: always
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
