package com.espritech.workerExpress221.config.exception;

import lombok.Getter;

@Getter
public enum ErrorCodes {

    WORKER_NOT_FOUND(400),
    MEDIA_NOT_FOUND(401),
    FILE_NOT_VALID(402),
    PROFESSION_NOT_FOUND(403),
    REGION_NOT_FOUND(405),
    DEPARTMENT_NOT_FOUND(406),

    REGION_NOT_VALID(407),
    DEPARTMENT_NOT_VALID(409),
    PROFESSION_NOT_VALID(410),
    WORKER_NOT_VALID(411),
    USER_NOT_FOUND(412),
    USER_NOT_VALID(413),
    NOT_AUTHORIZE(414),
    PUBLICITY_NOT_VALID(415),
    PUBLICITY_NOT_FOUND(416),
    CALLLOG_NOT_VALID(417),
    CALLLOG_NOT_FOUND(418),
    RATING_NOT_VALID(419),
    RATING_NOT_FOUND(420),
    REVIEW_WORKER_NOT_VALID(421),
    REVIEW_WORKER_NOT_FOUND(422),
    REVIEW_APP_NOT_VALID(423),
    SUB_PROFESSION_NOT_VALID(424),
    SUB_PROFESSION_NOT_FOUND(425),
    SUB_PROFESSION_FOUND(426),
    PROFESSION_FOUND(427),
    CNI_NOT_FOUND(428),
    CERTIFICATE_NOT_FOUND(429),
    EMAIL_SEND_NOT_VALID(430),
    CONFIGURATION_APP_NOT_VALID(431),
    CONFIGURATION_APP_NOT_FOUND(432);


  private final int code;

  ErrorCodes(int code) {
    this.code = code;
  }

}
